[phases.setup]
nixPkgs = ["python310", "python310Packages.pip"]

[phases.install]
cmds = ["cd v1/backend && pip install -r requirements.txt"]

[start]
cmd = "cd v1/backend && uvicorn server:app --host 0.0.0.0 --port $PORT"
