agent_name = "quickstart"
image = "inxfiona/quickstart:latest"
secret_set = "quickstart-secrets"
agent_profile = "agent-1x"

# RECOMMENDED: Set an image pull secret:
# https://docs.pipecat.ai/deployment/pipecat-cloud/fundamentals/secrets#image-pull-secrets
# image_credentials = "docker-hub-creds"

[scaling]
	min_agents = 1
